name: quizzie_thunder
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2 
  dio: ^5.1.2
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_fonts: ^6.2.1
  flutter_carousel_widget: ^2.2.0
  share_plus: ^9.0.0
  webview_flutter: ^4.7.0 
  flutter_svg: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  scoped_model: ^2.0.0
  shared_preferences: ^2.3.2
  google_mobile_ads: ^5.1.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2
  confirmation_success: ^0.0.2
  awesome_snackbar_content: ^0.1.4
  another_flutter_splash_screen: ^1.2.1
  intl_phone_field: ^3.2.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true #should generate android icon
  ios: true #should generate IOS icon
  image_path: "assets/images/cermatik.jpeg" 

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/  
    - assets/ikony/  
    - assets/icon/ 
    - assets/siroky/  
