
# fastlane/Fastfile
default_platform(:ios)
platform :ios do
 desc "Build and upload a new version to the App Store"
 lane :release do
 build_app(scheme: "Cermatik")
 upload_to_app_store(
 app_identifier: "cz.cermatik",
 api_key_path: "./ApiKey_OIHK2Q1IP5YN.p8",
 api_key_id: "785GTLYJ95",
 api_issuer: "222e1d65-de6a-40f0-85a8-bc60436cdba7"
 )
 end
end